package fluentd

func createFluentdContainerConfigProviderForKurtosis(httpPortNumber uint16) *fluentdContainerConfigProvider {
	fluentdConfig := newDefaultFluentdConfigForKurtosisCentralizedLogs(httpPortNumber)
	fluentdContainerConfigProviderObj := newFluentdContainerConfigProvider(fluentdConfig, httpPortNumber)
	return fluentdContainerConfigProviderObj
}
