version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/api/golang"
      - "/cli/cli"
      - "/cloud/api/golang"
      - "/connect-server"
      - "/container-engine-lib"
      - "/contexts-config-store"
      - "/core/files_artifacts_expander"
      - "/core/launcher"
      - "/core/server"
      - "/enclave-manager/api/golang"
      - "/enclave-manager/server"
      - "/engine/launcher"
      - "/engine/server"
      - "/grpc-file-transfer/golang"
      - "/internal_testsuites/golang"
      - "/kurtosis_version"
      - "/metrics-library/golang"
      - "/name_generator"
      - "/path-compression"
    schedule:
      interval: "weekly"
    groups:
      all-go-deps:
        group-by: dependency-name
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/api/typescript"
      - "/docs"
      - "/enclave-manager/web"
      - "/engine/frontend"
      - "/internal_testsuites/typescript"
    schedule:
      interval: "weekly"
    groups:
      all-npm-deps:
        group-by: dependency-name
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        group-by: dependency-name
        patterns:
          - "*"
