version: 2.1

executors:
  ubuntu_vm:
    machine:
      # This ubuntu-2004:202201-02 machine has a pre-installed Docker, so we are not using the CircleCI remote Docker when we
      # initiate this machine. More here: https://discuss.circleci.com/t/linux-machine-executor-images-2022-january-q1-update/42831
      image: ubuntu-2004:2023.07.1

jobs:
  k3d:
    executor: ubuntu_vm
    steps:
      - run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster create --servers 1 --wait --verbose
      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis version
      - run: |
          KURTOSIS_CONFIG_FILEPATH=$(kurtosis config path)
          echo -e "config-version: 2\nshould-send-metrics: false\nkurtosis-clusters:\n  docker:\n    type: docker\n  k3d-k3s-default:\n    type: kubernetes\n    config:\n       kubernetes-cluster-name: k3d-k3s-default\n       storage-class: standard\n       enclave-size-in-megabytes: 2048" > "$KURTOSIS_CONFIG_FILEPATH"
          KURTOSIS_CONFIG_DIR=$(dirname "$KURTOSIS_CONFIG_FILEPATH")
          KURTOSIS_CLUSTER_SETTING_FILEPATH="$KURTOSIS_CONFIG_DIR/cluster-setting"
          echo -n "k3d-k3s-default" > "$KURTOSIS_CLUSTER_SETTING_FILEPATH" 
      - run: |
          kurtosis engine start
      - run:
          command: "kurtosis gateway"
          background: true
      - run: |
          kurtosis enclave add
workflows:
  build:
    jobs:
      - k3d
