version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu:22.04

jobs:
  k3d:
    executor: ubuntu_vm
    steps:
      - run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster create --servers 1 kurtosis-k3d-cluster --wait
          kubectl get nodes

workflows:
  build:
    jobs:
      - k3d
