name: "Bug Report"
description: Report broken functionality
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: What version of the Kurtosis CLI were you running when you hit this bug?
      placeholder: e.g. 1.2.0
      description: |
        View the version of your Kurtosis CLI with `kurtosis version`.
    validations:
      required: true
  - type: input
    id: metrics-user-id
    attributes:
      label: (OPTIONAL) What is your metrics user ID?
      placeholder: e.g. 07d1472497dg44593e5520436603ca4c3423423bd608bec371f9343dxcf4b
      description: |
        Print your metrics user ID with `kurtosis analytics id`. This information helps us debug and fix issues quicker.
        [Read our metrics philosophy here](https://docs.kurtosis.com/explanations/metrics-philosophy).
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: What is the severity of this bug?
      multiple: false
      options:
      - Critical; I am blocked and Kurtosis is unusable to us because of this bug.
      - Painful; this is causing significant friction in my workflow.
      - Papercut; this bug is frustrating, but I have a workaround.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description & steps to reproduce
      description: |
        We can solve your issue faster when you provide logs, error text, screenshots, reproduction steps, [`kurtosis enclave dump`](https://docs.kurtosis.com/enclave-dump) output, [`kurtosis dump`](https://docs.kurtosis.com/dump) output, etc.
      placeholder: |
        When I run command '...' then the following error appears...

        To reproduce,
        1. Run command '...'
        2. Then do...
        3. Then try...

        Attached are the logs from 'kurtosis enclave dump'...
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behavior
      placeholder: |
         What should happen?
    validations:
      required: true
