blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/rjkj8m5C
    about: Join our Discord community.
  - name: Email
    url: mailto:feedback@kurtosistech.com
    about: Get in touch via email.
