name: "Docs Issue"
description: We are always striving to improve Kurtosis. Use this form to suggest a new feature or improvement. 
labels: ["docs"]
title: "[Docs]: "
assignees:
  - leeederek
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us improve our documentation. We value your feedback.
  - type: input
    id: url-link
    attributes:
      label: Where did you see an issue in our documentation? 
      placeholder: e.g. https://docs.kurtosis.com/explanations/architecture
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      placeholder: What is the issue you found in our documentation?
      description: |
        Consider adding screenshots or the exact part of the documentation language that you're filing this issue on.
      validations:
        required: true
