name: "Docs Issue"
description: Report an issue in our documentation
labels: ["docs"]
assignees:
  - leeederek
body:
  - type: input
    id: url-link
    attributes:
      label: Where did you see the issue in our documentation? 
      placeholder: e.g. https://docs.kurtosis.com/explanations/architecture
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      placeholder: |
        e.g. There is a typo in the sentence 'Kurtosis can be run as...' because...

        This is a screenshot...
      description: |
        Screenshots or copy-pasting the problematic text is very helpful.
    validations:
      required: true
