name: "Feature Request"
description: Suggest a new feature, improvement, or change 
labels: ["feature request"]
body:
  - type: textarea
    id: background-and-motivation
    attributes:
      label: Motivation & background
      placeholder: Code examples, screenshots, and references are very helpful here
      description: |
        What problem are you trying to solve? What are you looking to accomplish? What pain are you hitting?
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behaviour
      placeholder: Code examples, screenshots, and references are very helpful here
      description: |
        What would you like to happen?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      multiple: false
      options:
      - Critical; Kurtosis is unusable for us without it.
      - Painful; the lack of this feature makes using Kurtosis frictionful.
      - Nice to have; this feature would make using Kurtosis more enjoyable.
    validations:
      required: true
