name: "Feature Request"
description: Suggest a new feature, improvement, or change 
labels: ["feature request"]
body:
  - type: textarea
    id: background-and-motivation
    attributes:
      label: Background & motivation
      placeholder: |
        What problem are you trying to solve? What are you looking to accomplish?

        e.g. I'm trying to X, but Y...

        Code examples and screenshots help us a lot.
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behaviour
      placeholder: |
        What would you like to happen?

        e.g. The X should Y...
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      multiple: false
      options:
      - Critical; Kurtosis is unusable for me without it.
      - Painful; the lack of this feature makes using Kurtosis frictionful.
      - Nice to have; this feature would make using Kurtosis more enjoyable.
    validations:
      required: true
