// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+dts"
// @generated from file portal_daemon_service.proto (package portal_daemon_api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ForwardUserServicePortArgs, ForwardUserServicePortResponse, PortalPing, PortalPong } from "./portal_daemon_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service portal_daemon_api.KurtosisPortalDaemon
 */
export const KurtosisPortalDaemon = {
  typeName: "portal_daemon_api.KurtosisPortalDaemon",
  methods: {
    /**
     * To check availability
     *
     * @generated from rpc portal_daemon_api.KurtosisPortalDaemon.Ping
     */
    ping: {
      name: "Ping",
      I: PortalPing,
      O: PortalPong,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc portal_daemon_api.KurtosisPortalDaemon.ForwardUserServicePort
     */
    forwardUserServicePort: {
      name: "ForwardUserServicePort",
      I: ForwardUserServicePortArgs,
      O: ForwardUserServicePortResponse,
      kind: MethodKind.Unary,
    },
  }
};

