package kurtosis_plan_instruction

import (
	"github.com/kurtosis-tech/kurtosis/core/server/api_container/server/startosis_engine/instructions_plan"
	"github.com/kurtosis-tech/kurtosis/core/server/api_container/server/startosis_engine/instructions_plan/resolver"
	"github.com/kurtosis-tech/kurtosis/core/server/api_container/server/startosis_engine/kurtosis_starlark_framework"
	"github.com/kurtosis-tech/kurtosis/core/server/api_container/server/startosis_engine/startosis_errors"
	"go.starlark.net/starlark"
)

type KurtosisPlanInstruction struct {
	*kurtosis_starlark_framework.KurtosisBaseBuiltin

	Capabilities func() KurtosisPlanInstructionCapabilities

	DefaultDisplayArguments map[string]bool
}

// KurtosisPlanInstructionWrapper is a convenience wrapper to store the instructionQueue necessary in the
// CreateBuiltin next to the KurtosisPlanInstruction, without polluting its declaration
type KurtosisPlanInstructionWrapper struct {
	*KurtosisPlanInstruction

	instructionPlanMask *resolver.InstructionsPlanMask

	// TODO: This can be changed to KurtosisPlanInstructionInternal when we get rid of KurtosisInstruction
	instructionPlan *instructions_plan.InstructionsPlan
}

func NewKurtosisPlanInstructionWrapper(instruction *KurtosisPlanInstruction, instructionPlan *instructions_plan.InstructionsPlan, instructionPlanMask *resolver.InstructionsPlanMask) *KurtosisPlanInstructionWrapper {
	return &KurtosisPlanInstructionWrapper{
		KurtosisPlanInstruction: instruction,
		instructionPlanMask:     instructionPlanMask,
		instructionPlan:         instructionPlan,
	}
}

func (builtin *KurtosisPlanInstructionWrapper) CreateBuiltin() func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	return func(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
		wrappedBuiltin, interpretationErr := kurtosis_starlark_framework.WrapKurtosisBaseBuiltin(builtin.KurtosisBaseBuiltin, thread, args, kwargs)
		if interpretationErr != nil {
			return nil, interpretationErr
		}

		instructionWrapper := newKurtosisPlanInstructionInternal(wrappedBuiltin, builtin.Capabilities(), builtin.DefaultDisplayArguments)
		returnedFutureValue, interpretationErr := instructionWrapper.interpret()
		if interpretationErr != nil {
			return nil, interpretationErr
		}

		var instructionMaskMaybe *instructions_plan.ScheduledInstruction
		if builtin.instructionPlanMask.HasNext() {
			instructionMaskMaybe = builtin.instructionPlanMask.Next()
			if instructionMaskMaybe != nil && instructionMaskMaybe.GetInstruction().String() != instructionWrapper.String() {
				return nil, startosis_errors.NewInterpretationError(
					"The instruction mask provided to the interpreter was invalid with the set of instructions "+
						"generated by the interpreter. Instruction '%s' would have been masked by '%s', which seems "+
						"wrong. This is a Kurtosis internal error",
					instructionWrapper.String(),
					instructionMaskMaybe.GetInstruction().String())
			}
		}

		if instructionMaskMaybe != nil {
			// If there's a mask for this instruction, add the mask the plan and returned the mask's returned value
			builtin.instructionPlan.AddScheduledInstruction(instructionMaskMaybe).Executed(true).ImportedFromPreviousEnclavePlan(false)
			return instructionMaskMaybe.GetReturnedValue(), nil
		} else {
			// otherwise add the instruction as a new one to the plan and return its own returned value
			if err := builtin.instructionPlan.AddInstruction(instructionWrapper, returnedFutureValue); err != nil {
				return nil, startosis_errors.WrapWithInterpretationError(err,
					"Unable to add Kurtosis instruction '%s' at position '%s' to the current plan being assembled. This is a Kurtosis internal bug",
					instructionWrapper.String(),
					instructionWrapper.GetPositionInOriginalScript().String())
			}

			return returnedFutureValue, nil
		}
	}
}
