issues:
  exclude-rules:
    # Typecheck does not support embedded structs, so it fails when it tries to check this: suite.T() for this `type StartosisRequestWaitAssertTestSuite struct`.
    # there is a GitHub discussion for this topic here: https://github.com/golangci/golangci-lint/discussions/2287
    - path: "testsuite/startosis_request_wait_assert_test"
      linters:
        - typecheck