name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read
  
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.1
      with:
        configuration-path: .github/issue_labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
