name: Publish CLI

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to publish (e.g. 1.17.4)'
        required: true
        type: string

jobs:
  push-cli-artifacts:
    uses: ./.github/workflows/push-cli-artifacts.yml
    with:
      go-version: '1.26.0'
      checkout-ref: ${{ inputs.release_tag }}
    secrets:
      KURTOSISBOT_GITHUB_TOKEN: ${{ secrets.KURTOSISBOT_GITHUB_TOKEN }}
