name: Deploy documentation

on:
  push:
  merge_group:
  pull_request_target:
    # this is for forked pull requests - we can't pass down secrets; this allows us to pass down secrets
    # to build the cloudflare pages action
    types:
      - opened
      - labeled

env:
  HUGO_VERSION: '0.161.1'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    if: ${{
      github.repository == 'kurtosis-tech/kurtosis' &&
      (
      github.event_name == 'push' ||
      github.event_name == 'merge_group' ||
      (
      github.event_name == 'pull_request_target' &&
      github.event.action == 'labeled' &&
      github.event.pull_request.head.repo.fork == true &&
      contains(github.event.label.name, 'request-cf-deploy')
      ))
      }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Docs have changed
        run: |
          echo "DOCS_CHANGED=$(git --no-pager diff --exit-code origin/main...HEAD -- ':docs' > /dev/null; echo $?)" >> $GITHUB_OUTPUT
        id: docs-diff
      - name: Append changelog
        run: cat CHANGELOG.md >> docs/docs/changelog.md
        if: github.ref == 'refs/heads/main' || steps.docs-diff.outputs.DOCS_CHANGED != 0
      - name: Setup Hugo
        if: github.ref == 'refs/heads/main' || steps.docs-diff.outputs.DOCS_CHANGED != 0
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Hugo Build
        if: github.ref == 'refs/heads/main' || steps.docs-diff.outputs.DOCS_CHANGED != 0
        working-directory: docs
        run: hugo --gc --minify
      - name: Publish to Cloudflare Pages
        if: github.ref == 'refs/heads/main' || steps.docs-diff.outputs.DOCS_CHANGED != 0
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/build/ --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch=${GITHUB_REF##*/} --commit-message="${DEPLOY_COMMIT_MSG%%$'\n'*}" --commit-dirty=true
        env:
          DEPLOY_COMMIT_MSG: ${{ github.event.head_commit.message || github.sha }}
  reindex-website-main:
    runs-on: ubuntu-latest
    name: Update website search index via Algolia Crawler
    if: ${{
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
      }}
    steps:
      - uses: fjogeleit/http-request-action@551353b829c3646756b2ec2b3694f819d7957495 # v2.0.0
        with:
          url: "https://crawler.algolia.com/api/1/crawlers/${{ secrets.ALGOLIA_CRAWLER_ID }}/reindex"
          method: "POST"
          username: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
          password: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
          customHeaders: '{"Content-Type": "application/json"}'
    needs: publish
